[2024-02-26T22:34:36.688+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.load_data_into_the_table manual__2024-02-26T22:34:04.498004+00:00 [queued]>
[2024-02-26T22:34:36.707+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.load_data_into_the_table manual__2024-02-26T22:34:04.498004+00:00 [queued]>
[2024-02-26T22:34:36.708+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-26T22:34:36.735+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): load_data_into_the_table> on 2024-02-26 22:34:04.498004+00:00
[2024-02-26T22:34:36.742+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-02-26T22:34:36.747+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'load_data_into_the_table', 'manual__2024-02-26T22:34:04.498004+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmp291d0hws']
[2024-02-26T22:34:36.750+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask load_data_into_the_table
[2024-02-26T22:34:36.820+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.load_data_into_the_table manual__2024-02-26T22:34:04.498004+00:00 [running]> on host 5d25474dd79a
[2024-02-26T22:34:36.935+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='load_data_into_the_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T22:34:04.498004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T22:34:04.498004+00:00'
[2024-02-26T22:34:36.938+0000] {sql.py:276} INFO - Executing: 
                    COPY INTO Bangkok from @s3_stage file_format=csv_format;

            
[2024-02-26T22:34:36.954+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-26T22:34:36.968+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-26T22:34:36.969+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-02-26T22:34:36.971+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-26T22:34:37.354+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-26T22:34:37.435+0000] {cursor.py:1041} INFO - query execution done
[2024-02-26T22:34:37.436+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-26T22:34:37.436+0000] {sql.py:450} INFO - Running statement: COPY INTO Bangkok from @s3_stage file_format=csv_format;, parameters: None
[2024-02-26T22:34:37.437+0000] {cursor.py:1028} INFO - query: [COPY INTO Bangkok from @s3_stage file_format=csv_format;]
[2024-02-26T22:34:38.471+0000] {cursor.py:1041} INFO - query execution done
[2024-02-26T22:34:38.472+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-26T22:34:38.474+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-26T22:34:38.476+0000] {snowflake.py:400} INFO - Rows affected: 1
[2024-02-26T22:34:38.477+0000] {snowflake.py:401} INFO - Snowflake query id: 01b29e2a-3201-0126-0000-000805ce5121
[2024-02-26T22:34:38.478+0000] {cursor.py:1028} INFO - query: [COMMIT]
[2024-02-26T22:34:38.672+0000] {cursor.py:1041} INFO - query execution done
[2024-02-26T22:34:38.674+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-26T22:34:38.676+0000] {connection.py:718} INFO - closed
[2024-02-26T22:34:38.746+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-02-26T22:34:38.885+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=load_data_into_the_table, execution_date=20240226T223404, start_date=20240226T223436, end_date=20240226T223438
[2024-02-26T22:34:38.930+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-26T22:34:38.965+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
