[2024-02-12T11:02:05.098+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_redshift_dag.create_table scheduled__2024-02-12T10:30:00+00:00 [queued]>
[2024-02-12T11:02:05.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_redshift_dag.create_table scheduled__2024-02-12T10:30:00+00:00 [queued]>
[2024-02-12T11:02:05.114+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-02-12T11:02:05.133+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table> on 2024-02-12 10:30:00+00:00
[2024-02-12T11:02:05.140+0000] {standard_task_runner.py:60} INFO - Started process 615 to run task
[2024-02-12T11:02:05.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_redshift_dag', 'create_table', 'scheduled__2024-02-12T10:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/s3 _to_redshift.py', '--cfg-path', '/tmp/tmpfd0ye4t2']
[2024-02-12T11:02:05.149+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask create_table
[2024-02-12T11:02:05.244+0000] {task_command.py:423} INFO - Running <TaskInstance: test_redshift_dag.create_table scheduled__2024-02-12T10:30:00+00:00 [running]> on host f6c6a9bbd38e
[2024-02-12T11:02:05.338+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='test_redshift_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T10:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T10:30:00+00:00'
[2024-02-12T11:02:05.340+0000] {sql.py:276} INFO - Executing:  
                CREATE TABLE test.weather_demo_table (
                    "Time of Record" datetime,
                    City varchar(25),
                    Description varchar(25),
                    "Temperature (C)" float,
                    "Feels Like (C)" float,
                    "Minimun Temp (C)" float,
                    "Maximum Temp (C)" float,
                    Pressure integer,
                    Humidty integer,
                    "Wind Speed" float,
                    "Sunrise (Local Time)" datetime,
                    "Sunset (Local Time)" datetime
                )
    
[2024-02-12T11:02:05.351+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2024-02-12T11:02:05.363+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2024-02-12T11:02:05.413+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "redshift-cluster-1.cknvvpe46ntw.ap-southeast-1.redshift.amazonaws.com" to address: Name or service not known

[2024-02-12T11:02:05.425+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=test_redshift_dag, task_id=create_table, execution_date=20240212T103000, start_date=20240212T110205, end_date=20240212T110205
[2024-02-12T11:02:05.443+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task create_table (could not translate host name "redshift-cluster-1.cknvvpe46ntw.ap-southeast-1.redshift.amazonaws.com" to address: Name or service not known
; 615)
[2024-02-12T11:02:05.479+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-12T11:02:05.511+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
