[2024-02-12T22:30:23.405+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_snowflake_external_stage scheduled__2024-02-12T22:00:00+00:00 [queued]>
[2024-02-12T22:30:23.416+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_snowflake_external_stage scheduled__2024-02-12T22:00:00+00:00 [queued]>
[2024-02-12T22:30:23.417+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-12T22:30:23.436+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): create_snowflake_external_stage> on 2024-02-12 22:00:00+00:00
[2024-02-12T22:30:23.443+0000] {standard_task_runner.py:60} INFO - Started process 157 to run task
[2024-02-12T22:30:23.448+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_snowflake_external_stage', 'scheduled__2024-02-12T22:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmphr8dph0a']
[2024-02-12T22:30:23.450+0000] {standard_task_runner.py:88} INFO - Job 136: Subtask create_snowflake_external_stage
[2024-02-12T22:30:23.518+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.create_snowflake_external_stage scheduled__2024-02-12T22:00:00+00:00 [running]> on host 3bd3b2605e24
[2024-02-12T22:30:23.640+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='create_snowflake_external_stage' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T22:00:00+00:00'
[2024-02-12T22:30:23.642+0000] {sql.py:276} INFO - Executing: 
                    CREATE OR REPLACE stage s3_stage
                        URL = "s3://bucket-weather-data/current_weather_data_portland_12022024223007.csv"
                        credentials=(aws_key_id='AKIAVRUVRXEM77SSYROY' aws_secret_key='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');
                
            
[2024-02-12T22:30:23.657+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-12T22:30:23.670+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-12T22:30:23.671+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-02-12T22:30:23.672+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-12T22:30:24.120+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-12T22:30:24.202+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T22:30:24.203+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T22:30:24.204+0000] {sql.py:450} INFO - Running statement: CREATE OR REPLACE stage s3_stage
                        URL = "s3://bucket-weather-data/current_weather_data_portland_12022024223007.csv"
                        credentials=(aws_key_id='AKIAVRUVRXEM77SSYROY' aws_secret_key='6K0K3J/4qOYp3hPjFgDcayWYKoNNZF9DmVD581vs');, parameters: None
[2024-02-12T22:30:24.205+0000] {cursor.py:1028} INFO - query: [CREATE OR REPLACE stage s3_stage URL = "s3://bucket-weather-data/current_weather...]
[2024-02-12T22:30:24.322+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T22:30:24.323+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T22:30:24.324+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-12T22:30:24.329+0000] {snowflake.py:400} INFO - Rows affected: 1
[2024-02-12T22:30:24.332+0000] {snowflake.py:401} INFO - Snowflake query id: 01b24f66-3200-fe5c-0007-a44e00011686
[2024-02-12T22:30:24.334+0000] {cursor.py:1028} INFO - query: [COMMIT]
[2024-02-12T22:30:24.416+0000] {cursor.py:1041} INFO - query execution done
[2024-02-12T22:30:24.417+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-12T22:30:24.418+0000] {connection.py:718} INFO - closed
[2024-02-12T22:30:24.480+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-02-12T22:30:24.574+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=create_snowflake_external_stage, execution_date=20240212T220000, start_date=20240212T223023, end_date=20240212T223024
[2024-02-12T22:30:24.628+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-12T22:30:24.704+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
